import { app, BrowserWindow, Rectangle } from 'electron';
import fs from 'fs';
import { TabWebView } from '../main/webView/tab';
import { LlmApi } from './api';
import { PromptRun } from './promptRun';
import { WireActionWithWaitAndRec } from './types';
import { ToRendererIpc } from '../contracts/toRenderer';
import { Util } from '../webView/util';
import { PromptAttachment } from '../schema/attachments';
import { WireTabAction } from './execution.schema';
import { CommonUtil } from '../utils/common';
import './profile/smartAction.registry';
// import { CommonUtil } from '../utils/common';

const DEBUG_CONFIRM_ALL_ACTIONS = false;
const testPrompt: { user: string; system: string } | null = {
  system: `[system]
a web base agentic workflow task engine, perform action in agent browser according to pre-processed task guide.

[role]
you are an executor, working on task with web page. taking user tasks in prompt [goal] section and compile into actions to perform on the browser.
you are responsible for give actions, verify result inside the reasoning process on your own.

[customised html rule]
the html contains all elements with content on the page include those out of current viewport. it skipped some of the non-significant elements like middle makeup tags.
each visible tag has xywh=x,y,width,height, some tag may has hls means highlightStyle.
all visible tag comes with id, use it to query element in action. it is dynamical generated by engine, may change if element moved or removed in dynamic ui. avoid delegate id in [todo] or tip.
sw & sh will be provided if the element body is scrollable.
val is the value of input, select, textarea.
use only the elements provided in current [html], and work with their id in action. make sure the id you use appear in current [html], cached [html] in previous session may have expired.

[response in valid json format]

type ID=string;//from id attr of html element, no wrap/prefix/suffix
type Selector=ID |{ id:ID, argKeys:(string|null)[]};

type WireWait={ to?:number } & ( // wait timeout in ms
 |{ t:'network';a:'idle0'|'idle2' }
 |{ t:'time';ms:number }
)

type WireAction=
{
  k:'fillForm';
  q:'__e'|Selector;//form id
  data:{f:string|Selector;v:string|string[]}[];//field name or selector and value to fill, string or js argument tpl
}|
 |{
   k:'todo';
   a:'add'|'cancel'|'done';
   pos?:number;
   add?string[];//todos to add
  }
 |{
   k:'mouse';
   a:'click'|'dblclick'|'mouseover'|'mouseDown'|'mouseUp'|'mouseenter'|'mousemove';
   q:Selector;
   repeat?:number;
  }
 |{
   k:'scroll';
   to:Selector|[number/*x*/, number/*y*/];
   over?:Selector;// default to window
  }
 |{
   k:'focus';
   q:Selector;
  }
 |{
   k:'dragAndDrop';
   sq:Selector;// src QuerySelector
   dq?:Selector;// dst QuerySelector
   mv?:{ x:number;y:number }|null;
  }
 |{
   k:'key';
   key:string;// single key, use input for typing words
   a:'keyDown'|'keyUp'|'keyPress';//always use press for typing, unless required/need delay
   q?:Selector;
   c?:boolean;// ctrl
   al?:boolean;// alt
   s?:boolean;// shift
   m?:boolean;// meta
   repeat?:number;
  }
 |{
   k:'input';// for input, textarea, contentEditable, select, also upload file with path in v
   q:Selector;
   v:string|string[];// input value, array for multiple select/files
   c?:'noClear';// without this will clear before typing
  }
 |{
   k:'botherUser'; //only use when goal cannot be continued.
   warn:string;
   missingInfos?:string[];
   rc?:string|null;// followup prompt
  }
 |{
   k:'setArg'; //it is a huge waste for read value with this
   // key value pair
   kv:Record<string, string |{q:Selector, attr?:'textContent'|string}>;//str value or from element, attr default textContent
  }
 |{
   k:'extraGoal'; //very high risk, do not use unless goal explicitly asked to accept requirement/advise from delegated source
   g: string;
  }
 |{
   k:'url';
   u:'next'|'forward'|'reload';
  }
 |{
   k:'tab';
   id:number;// switch to id, -1=new
   url?:string;// go to url on switch
  }
 |{
   k:'selectTxt';
   q:Selector;
   txt:string;
  }
 |{
   k:'download';
   a:Selector;
   t:'link'|'img'|'bg-img';// what to download
   filename?:string;// filename to read in downstream
  }
 |{
   k:'screenshot';//must not use after action that change page status, like click link, submit form, etc.
   filename:string;//png
   a?:Selector;
  };

type WireStep={
 intent:string;
 risk:'h'|'m'|'l';
 action:WireAction;
 pre?:WireWait // wait BEFORE this action, most of the time engine can handle it automatically
 post?:WireWait|// wait AFTER this action, most of the time engine can handle it automatically
  {
   t:'waitMsg';// only use when ask to wait for new msg/reply in messager dialog / new email in email inbox, **MUST NOT ADD ACTION AFTER THIS**
   q:Selector;// dialog container, email list etc
   id1st:string;// first msg/email dom id in list
   idLast:string;// last msg/email dom id in list
  }
}

type AttachementDesc={
 name:string;
 desc:string;
};

type LlmWireResult={
 a:WireStep[];// steps 
 e?:string;// error
 next?:{
  sc?:boolean;// require screenshot
  tip:string;//advisory tip for next executor, very short, add todo if > 15 words
  readFiles?:string[];// attach readable files only when you really need the content in file
  descAttachment?:AttachementDesc[];
 };
 resp?:string; // only when goal completely done or could not continue
};

**only valid JSON response is acceptable, markdown code block quoting will cause error**`,
  user: `[every request]
- [goal] will be in absolute priority, while [todo] include breakdown tasks from [goal] and additional task from process. Execution loop will stop once [todo] is all done.
- [todo] & [performed actions] will provided in followup prompts, take what have been done into account to avoid duplication, just do the new actions.
- Updated UI state is always provide by the [html].
- take [html] as source of truth or verification, not rely on arguments.
- setArg is used only for **carry context over page navigations & returning result to user**, not verify or read data.
- do not consider setArg as a way to read data, it will not give any extra info and waste time / tokens.
- ask yourself 2 questions before setArg, unnecessary arguments consider expensive and confusing, you need at least 1 exact yes answer to perform it:
  - if the value will disappear from html after your actions and required by downstream(remember they have [html]) or
  - if the goal ask to return/send the value explicitly(not over interpret)
- when asked to verify result, **ONLY USE [html]** to check against expected value
- when the argument value is coming from attachment, you must add filename to the key, like invoice.pdf-total.
- when receive attachment without description in readable file list other than screenshot.jpg, use next.descAttachment to shortly describe the file content for giving context to downstream
- file from download action can use immediately in next, just put the same filename in attach and download action.
- file should only be read on demand, and store necessary info in argument, do not require reading in every prompt.
- file list is automatically stored across whole session, no need to remention in any context.
- if user asked to wait for email/message, **waitMsg MUST DIRECTLY APPLY TO POST WAIT OF TRIGGER ACTION**. put in next may cause missing event.
- always open new tab if you need to switch task to a new website, retain the status of current page for reuse.

[safety check]
- links to external origin will give href, **MUST CHECK the url before click**, make sure matches its description. fraud is common in search engines or sns.
- **YOU MUST AVOID all kind of imagination official domain**, like amason.com, herms.co, apple.dev etc, especially looking to shop / transaction unless the goal override it.

[action guide]
- user task prompt may contain task work across multiple pages. You only plan actions doable in **the current content found in [html]**.
- every action need to be able to connect with **at least one element** in [html] provided, otherwise it is invalid.
- when task cannot be continue with current info, try perform possible actions and put followup prompt in [todo] or next.tiop. content may appear after that and it will resent after page state changed automatically with page updates.
- limit actions to 5 in one batch of response to avoid losing attention, it may even be fewer if the action is in high risk, put the remaining in [todo] or tip.
- some action like mouse click and key press can repeat multiple times by setting repeat, interval will be set by engine. prefer repeat over sending multiple actions.
- All actions operate only on the currently visible page content by default. Searching, or navigating for extra is not allowed unless the task explicitly asks for it.
- Destructive actions must be bound to a visible UI element.Keyboard shortcuts are not allowed for delete/remove unless explicitly requested by the task or stated on the UI.
- For multiple fields form, submit action must appear as an isolated response with single action. put in tip and remind next executor to verify input and do submit if inputs are valid.
- set pre/post hook ONLY IF it is **required by the workflow**. ordinary waiting or rerender/reload event will be handled by engine.

- you should:
- focus on the [mission] if exist while not conflict with the [goal], use [performed actions] to determine the current status in task.
- explain intention in WireStep.intent with very short natual language & argument before action, like \\"click the submit button\\", \\"fill in user name with $args.username\\" etc
- always mention argument & key in intention if they involved in the element lookup or action.
- read value and verify result by looking at [html], browser actions cannot help unless you need trigger some specific event to reveal values.
- assign a risk level to each step
- assume the url is opened and perform task on current page.
- you may return result by setting argument.
- provide key actions. browser engine will trigger pre-required action if possible, like focus before input, scroll and mouse move before click etc.
- only use next.sc in case of the html does not make much sense on task prompt, like many of media tags without alt/title.
- focus on [mission] or [action error] if they appear in task prompt if they align with the [goal].
- **only botherUser when the task is really uncertain or impossible** to be done, like missing info, large amount of transactions. Uncertainty alone is NOT a reason to bother user.

- Irreversible or high-impact actions (e.g. submitting critical forms, confirming payments, deleting data):
   - Do NOT use trial and error.
   - Only perform them when the outcome is clear and verified.
   - If required information is missing or the outcome is uncertain, use botherUser.
   - mark as high risk.

- Reversible or non-critical actions (e.g. navigation, opening widgets, clicking controls, changing views):
   - You MUST attempt a reasonable action and observe the result.
   - Perform at most one exploratory attempt per control. Decide using the lowest-risk option.
   - Always trial with one single step if uncertain and mention it in tip, like \\"The current state is X, I have tried click Y buttom, see how it behaves and decide the next towards the goal.\\".
   - Observe what changed. Use the result of the attempt to decide the next step.
   - If the result clarifies the behavior, continue.
   - Engine will bother user after hard limit of attempts reached.
   - Escalate to botherUser only as a last resort.

- todo rules:
- todo is a check list for the whole session, breakdown [goal] into atomic task in order, keep them in similar wording & arguments from original prompt.
- the session will terminate when todo items are all done, make sure you add something if goal is not done.
- mark todo item done/cancel whenever status change, you can always help previous executor to mark done for todo item if you found it done from [preformed actions].
- if [goal] explicitly said you should take task during the task, say get task/advise/follow-guide etc from email/message, you must add those to todo with suitable pos.
- page state will be updated and resend together with the performed actions, avoid mentioning in todo to confuse downstream executor.
- let downstream executor decide the action detail, only give high level, atomic mission.
- [goal] will be sent in every prompt, do not repeat in todo.

- tip rules:
- if argument is in use, always mention the key instead of value.
- write tip base on assumption that all waiting and action has been done, tell the next executor what to do directly without mention after / wait action complete.
- require screenshot is expensive, ONLY when the necessary info is likely only appear on media(canvas, svg, img etc), or the html layout is not making much sense.

- risk levels:
- risk = 'l'|'m'|'h' - 'l' (low) = scroll, click navigation link/button, mouse over, simple search, open page
- 'm' (mid) = fill form fields, drag & drop, submit data
- 'h' (high) = delete/remove, payment/checkout, irreversible settings, sensitive data operations
- always prioritise caution if user prompt mentions danger, careful, payment, delete, confidential data, or irreversible actions.
- risk will be handle separately in engine, just mark levels appropriately and move on smoothly.

[dynamic action]
when you use any key from arguments for element lookup, like html or label contains certain argument.key, which may appeared in WireStep.intent, you must **put the used argument keys in Selector.argKeys**. otherwise put empty array.
argument can be use in all input, url or other **string field** with template string, use like \${args.linkTitle}, make sure args is use within string template.
javascript string methods may apply to args in string template, like args.linkTitle.toLowerCase().replace(/s+/g, '-')
the only legal string format are plain text and args string template **start with '\${args.'** like \${args.linkTitle}, js code other than these will cause error.
  use argument tpl in number or object field cause error, covert to other format on your own and use as hardcode if necessary.



  [url]
  runever://benchmark/#/email

  [viewport]
  w=1370 h=916

  [html]
  <script>const font = {\"ff0\":\"\\\"Fira Sans\\\", \\\"Gill Sans\\\", \\\"Trebuchet MS\\\", sans-serif\",\"ff1\":\"\\\"Google Sans\\\", Roboto, Arial, sans-serif\"};
  const hls = {\"#0\":\"16px / 24px ff1 #222\",\"#1\":\"24px / 31.9992px ff1 #222\",\"#2\":\"500 14px / 21px ff1 #17e\",\"#3\":\"500 14px / 19.6px ff1 #17e\",\"#4\":\"500 14px / 21px ff1 #fff\",\"#5\":\"14px / 19.6px ff1 #566\",\"#6\":\"16px / 24px ff1 #111\"};</script><div id=__f hls=6><h2 id=__0 hls=1>Sign in</h2><p id=__1 hls=0>to continue to RMail</p><form id=__e label=fields:2><div id=__4><input id=__2 val= name=email placeholder=\" \" required=1 type=email hls=0 /><label covered>Email or phone</label></div><div id=__7><input id=__5 val= name=password placeholder=\" \" required=1 type=password hls=0 /><label covered>Password</label></div><a id=__8 hls=2>Forgot email?</a><div id=__a hls=5>Not your computer? Use Guest mode to sign in privately.<a id=__9 hls=3>Learn more</a></div><div id=__d><button id=__b hls=2>Create account</button><button id=__c type=submit hls=4>Next</button></div></form></div> //0

  [argument keys]
  (no keys)

  [form guide]
  - always use fillForm over input 1 by 1
  - make sure provide all info you know about the form, if data is from files, attach them in fs0

  [goal]
  email platform url: runever://benchmark/#/email

  ordering platform url: runever://benchmark/#/pos

  messager url: runever://benchmark/#/im

  do not bother user

  login to email account with:

  email: pikachu@pokemon.com

  password: P@ssword321

  if there is new order email, get order detail from email body or attachment. then go to pos system, login with same user pass as email. create order with detail from the the order form. in order preview page if the amount is > 1000, screenshot and go to messager to ask for manager dillion's approve with screenshot and source of order, follow what they advise if so. then go to order list and download the invoice. go to email and reply the client[todo 0/0]
  
  [todo 0/0]
  **you are first executor**, you must use todo action to split the prompt unless you can finish it in few actions`,
};

export class WebViewLlmSession {
  private static readonly PADDING = 0;
  private static readonly DEFAULT_TABBAR_HEIGHT = 112;
  private static readonly DEFAULT_SIDEBAR_WIDTH = 430;

  public readableFiles: Map<string, PromptAttachment> = new Map();
  private runsByRequestId = new Map<number, PromptRun>();
  private runQueue: number[] = [];
  private activeRequestId: number | null = null;
  private inFlightAction = false;
  private actionIdToRequestId = new Map<number, number>();
  private nextActionId = 0;
  private lastStartedRequestId: number | null = null;
  private snapshotTimer: NodeJS.Timeout | null = null;
  private snapshotPending = false;
  private tabsById = new Map<number, TabWebView>();
  private focusedTab: TabWebView | null = null;
  private userInputResolvers = new Map<
    number,
    (answer: Record<string, string>) => void
  >();

  constructor(private mainWindow: BrowserWindow) {}

  registerTab(tab: TabWebView) {
    this.tabsById.set(tab.webView.webContents.id, tab);
    if (tab.bounds.width > 0 && tab.bounds.height > 0) {
      tab.focus();
      this.runsByRequestId
        .get(this.lastStartedRequestId ?? -1)
        ?.runningSession[0]?.addLog(
          `Populated tab and focused [${tab.webView.webContents.getTitle()}]`,
        );
    }
  }

  unregisterTab(frameId: number) {
    this.tabsById.delete(frameId);
  }

  getTab(frameId: number) {
    return this.tabsById.get(frameId);
  }

  getAnyTab() {
    return this.tabsById.values().next().value as TabWebView | undefined;
  }

  getTabsById() {
    return this.tabsById;
  }

  isFocused(tab: TabWebView) {
    return this.focusedTab === tab;
  }

  focusTab(tab: TabWebView) {
    if (this.focusedTab && this.focusedTab !== tab) {
      this.focusedTab.blur();
    }
    this.focusedTab = tab;
  }

  getFocusedTab() {
    return this.focusedTab;
  }

  getSafeBounds(
    opts: {
      sidebarWidth?: number;
      tabbarHeight?: number;
      viewportWidth?: number;
    } = {},
  ) {
    const sidebarWidth =
      opts.sidebarWidth ?? WebViewLlmSession.DEFAULT_SIDEBAR_WIDTH;
    const tabbarHeight =
      opts.tabbarHeight ?? WebViewLlmSession.DEFAULT_TABBAR_HEIGHT;

    const win = this.mainWindow?.getBounds();
    const devtoolsWidth = (win?.width ?? 1024) - (opts.viewportWidth ?? 0);
    const width = Math.max(
      320,
      (win?.width ?? 1024) -
        sidebarWidth -
        devtoolsWidth -
        WebViewLlmSession.PADDING * 2,
    );
    const height = Math.max(
      320,
      (win?.height ?? 728) - tabbarHeight - WebViewLlmSession.PADDING * 2,
    );
    return {
      x: WebViewLlmSession.PADDING,
      y: tabbarHeight + WebViewLlmSession.PADDING,
      width,
      height,
    };
  }

  createTab(detail: { url: string; bounds?: Rectangle }) {
    const bounds = detail.bounds ?? this.getSafeBounds();
    const wvTab = new TabWebView(detail.url, bounds, this.mainWindow, this);
    const frameId = wvTab.webView.webContents.id;
    wvTab.webView.webContents.once('destroyed', () => this.cleanupTab(frameId));
    wvTab.webView.webContents.on('render-process-gone', () =>
      this.cleanupTab(frameId),
    );
    this.mainWindow?.contentView.addChildView(wvTab.webView);
    this.registerTab(wvTab);
    return { id: frameId };
  }

  async operateTab(detail: {
    id: number;
    bounds?: Rectangle;
    url?: string;
    viewportWidth?: number;
    exeScript?: string;
    close?: boolean;
    visible?: boolean;
    sidebarWidth?: number;
    tabbarHeight?: number;
  }) {
    const frameId = detail.id;
    const wvTab = this.getTab(frameId);
    if (!wvTab) return { error: 'Tab not found' };
    let response;
    if (detail.close) {
      // Ensure any in-flight prompt/task is stopped before destroying webContents.
      wvTab.stopPrompt();
      wvTab.webView.setVisible(false);
      this.mainWindow?.contentView.removeChildView(wvTab.webView);
      this.unregisterTab(frameId);
      if (!wvTab.webView.webContents.isDestroyed()) {
        wvTab.webView.webContents.close();
      }
      response = 'closed';
    } else {
      if (detail.visible !== undefined) {
        wvTab.webView.setVisible(detail.visible);
        if (detail.visible) {
          wvTab.focus();
        }
      }
      if (detail.bounds) {
        wvTab.webView.setBounds(detail.bounds);
      } else if (!detail.url && !detail.exeScript) {
        wvTab.webView.setBounds(
          this.getSafeBounds({
            sidebarWidth:
              detail.sidebarWidth ?? WebViewLlmSession.DEFAULT_SIDEBAR_WIDTH,
            tabbarHeight:
              detail.tabbarHeight ?? WebViewLlmSession.DEFAULT_TABBAR_HEIGHT,
            viewportWidth: detail.viewportWidth,
          }),
        );
      }
      if (detail.url) {
        wvTab.webView.webContents.loadURL(detail.url);
        await Util.sleep(1000);
      }
      if (detail.exeScript) {
        response = await wvTab.webView.webContents.executeJavaScript(
          detail.exeScript,
        );
      }
    }
    return { response };
  }

  tabsCount() {
    return this.tabsById.size;
  }

  listTabs() {
    const { focusedTab } = this;
    return Array.from(this.tabsById.values()).map((tab) => ({
      id: tab.frameIds.values().next().value,
      title: tab.webView.webContents.getTitle(),
      url: tab.url.length > 100 ? `${tab.url.slice(0, 100)}...` : tab.url,
      focused: tab === focusedTab,
    }));
  }

  resolveUserInput(responseId: number, answer: Record<string, string>) {
    const resolver = this.userInputResolvers.get(responseId);
    if (!resolver) return;
    this.userInputResolvers.delete(responseId);
    resolver(answer);
  }

  async askUserInput<
    Q extends Record<
      string,
      | {
          type: 'string';
        }
      | {
          type: 'select';
          options: string[];
        }
    >,
  >(
    message: string,
    questions: Q,
  ): Promise<Record<Extract<keyof Q, string>, string>> {
    const responseId = Date.now() * 100 + Math.floor(Math.random() * 100);
    const promise = new Promise<Record<Extract<keyof Q, string>, string>>(
      (resolve) => {
        this.userInputResolvers.set(responseId, resolve as any);
      },
    );
    ToRendererIpc.toUser.send(this.mainWindow.webContents, {
      type: 'prompt',
      message,
      questions,
      responseId,
    });
    return promise;
  }

  async runPrompt(
    requestId: number,
    prompt: string,
    args?: Record<string, string>,
    attachments?: PromptAttachment[],
    reasoningEffort?: LlmApi.ReasoningEffort,
    modelType?: LlmApi.LlmModelType,
    frameId?: number,
  ): Promise<string | undefined> {
    const tab = typeof frameId === 'number' ? this.getTab(frameId) : undefined;
    const target = tab ?? this.focusedTab ?? this.getAnyTab();
    if (!target) return 'Tab not found';

    if (prompt === 'run test' && testPrompt) {
      const promises: Promise<string>[] = [];
      for (let i = 0; i < 3; i++) {
        const stream = LlmApi.queryLLMApi(
          testPrompt.user,
          testPrompt.system,
          null,
          `test_${Date.now()}_${i}`,
          'mid',
          'low',
        );
        promises.push(LlmApi.wrapStream(stream).catch((e) => e.message));
      }
      const result: string[] = await Promise.all(promises);
      console.info(
        'result:',
        `${app.getPath('userData')}/prompt-lab/test${new Date().toISOString().replace(/[^0-9]/g, '')}.json`,
        result,
      );
      try {
        fs.mkdirSync(`${app.getPath('userData')}/prompt-lab`);
      } catch (e) {
        console.log(e);
      }
      try {
        fs.writeFileSync(
          `${app.getPath('userData')}/prompt-lab/test${new Date().toISOString().replace(/[^0-9]/g, '')}.json`,
          JSON.stringify(result, null, 2),
        );
      } catch (e) {
        console.log(e);
      }
      return undefined;
    }

    try {
      if (!target) return 'Tab not found';
      const stream = this.startPrompt(
        requestId,
        target,
        prompt,
        args,
        attachments, // attachments
        reasoningEffort,
        modelType,
      );
      let response;
      console.info('stream:', stream);
      while ((response = await stream.next())) {
        if (!response.done) {
          console.info('pushPromptResponse:', response.value);
          target.pushPromptResponse(requestId, response.value);
        } else {
          break;
        }
      }
    } catch (e) {
      console.error('runPrompt error:', e);
      return Util.formatError(e);
    }
    return undefined;
  }

  startPrompt(
    requestId: number,
    tab: TabWebView,
    promptTxt: string,
    args?: Record<string, string>,
    attachments?: PromptAttachment[],
    reasoningEffort?: LlmApi.ReasoningEffort,
    modelType?: LlmApi.LlmModelType,
  ) {
    const existing = this.runsByRequestId.get(requestId);
    if (existing) existing.stop();

    const run = new PromptRun(this, tab, requestId);
    attachments
      ?.filter((a) => !!a.data)
      .forEach((a) => {
        this.readableFiles.set(a.name, a);
      });
    this.runsByRequestId.set(requestId, run);
    this.lastStartedRequestId = requestId;
    this.scheduleSnapshotEmit();
    return run.initPrompt(
      promptTxt,
      args,
      reasoningEffort,
      modelType,
      attachments?.map((f) => f.name),
    );
  }

  stopPrompt(requestId?: number) {
    const id = requestId ?? this.lastStartedRequestId;
    if (id === null) return { stopped: false, error: 'No prompt to stop' };
    const run = this.runsByRequestId.get(id);
    if (!run) return { stopped: false, error: 'Prompt not found' };

    run.stop();
    this.runQueue = this.runQueue.filter((v) => v !== id);
    if (this.activeRequestId === id) {
      this.activeRequestId = null;
      this.inFlightAction = false;
    }
    this.cleanupActionMapForRequest(id);
    this.scheduleSnapshotEmit();
    this.pump();
    return { stopped: true };
  }

  resumeAll() {
    for (const [requestId, run] of this.runsByRequestId.entries()) {
      if (!run.stopRequested && run.getNextAction()) {
        this.ensureRunLocked(requestId);
        this.enqueueRun(requestId);
      }
    }
  }

  allocActionId(requestId: number) {
    const actionId = this.nextActionId++;
    this.actionIdToRequestId.set(actionId, requestId);
    return actionId;
  }

  ensureRunLocked(requestId: number) {
    const run = this.runsByRequestId.get(requestId);
    if (!run || run.stopRequested) return;
    if (run.browserActionLock.tryLock()) {
      run.browserActionLock.wait
        .then(() => {
          if (this.activeRequestId === requestId) {
            this.activeRequestId = null;
            this.inFlightAction = false;
            this.scheduleSnapshotEmit();
          }
          this.pump();
        })
        .catch((err) => {
          console.error('Error waiting for browser action lock:', err);
        });
    }
  }

  enqueueRun(requestId: number) {
    if (!this.runsByRequestId.has(requestId)) return;
    if (this.activeRequestId === requestId) {
      this.pump();
      return;
    }
    if (!this.runQueue.includes(requestId)) {
      this.runQueue.push(requestId);
      this.scheduleSnapshotEmit();
    }
    this.pump();
  }

  actionDone(actionId: number, argsDelta?: Record<string, string> | undefined) {
    const requestId = this.actionIdToRequestId.get(actionId);
    if (requestId === undefined) return;
    const run = this.runsByRequestId.get(requestId);
    if (!run) return;
    run.actionDone(actionId, argsDelta);
    if (this.activeRequestId === requestId) {
      this.inFlightAction = false;
      this.pump();
    }
    this.scheduleSnapshotEmit();
  }

  actionError(actionId: number, error: string) {
    const requestId = this.actionIdToRequestId.get(actionId);
    if (requestId === undefined) return;
    const run = this.runsByRequestId.get(requestId);
    if (!run) return;
    run.actionError(actionId, error);
  }

  notifySnapshotChanged() {
    this.scheduleSnapshotEmit();
  }

  private async confirmAndDispatchHighRiskAction(
    requestId: number,
    run: PromptRun,
    nextAction: WireActionWithWaitAndRec,
  ) {
    try {
      const approved = await run.tab.confirmHighRiskAction(
        nextAction.intent ?? 'High risk action',
      );
      if (!approved) {
        this.stopPrompt(requestId);
        return;
      }
      // Keep `inFlightAction = true` until actionDone/actionError arrives.
      run.tab.pushActions([nextAction], run.args);
    } catch (err) {
      console.error('High risk approval failed:', err);
      this.stopPrompt(requestId);
    }
  }

  private collectArgKeysFromValue(value: unknown, keys: Set<string>) {
    if (typeof value === 'string') {
      const rx = /\$\{args\.([a-zA-Z0-9_]+)\}/g;
      let match: RegExpExecArray | null;
      while ((match = rx.exec(value))) {
        if (match[1]) keys.add(match[1]);
      }
      return;
    }
    if (Array.isArray(value)) {
      value.forEach((v) => this.collectArgKeysFromValue(v, keys));
      return;
    }
    if (!value || typeof value !== 'object') return;

    const anyValue = value as any;
    if (Array.isArray(anyValue.argKeys)) {
      anyValue.argKeys.forEach((k: unknown) => {
        if (typeof k === 'string' && k.trim()) keys.add(k);
      });
    }

    Object.values(anyValue).forEach((v) =>
      this.collectArgKeysFromValue(v, keys),
    );
  }

  private getMissingArgKeys(
    run: PromptRun,
    nextAction: WireActionWithWaitAndRec,
  ) {
    const keys = new Set<string>();
    this.collectArgKeysFromValue(nextAction.action, keys);
    this.collectArgKeysFromValue(nextAction.pre, keys);
    this.collectArgKeysFromValue(nextAction.post, keys);
    return Array.from(keys).filter((k) => {
      const v = (run.args as any)?.[k];
      if (v === undefined || v === null) return true;
      return String(v).trim().length === 0;
    });
  }

  private async ensureArgsForAction(
    requestId: number,
    run: PromptRun,
    _nextAction: WireActionWithWaitAndRec,
  ) {
    const missingKeys = new Set<string>();
    const lookAhead = run.getRemainActions().slice(0, 8);
    for (const action of lookAhead) {
      this.getMissingArgKeys(run, action).forEach((k) => missingKeys.add(k));
    }
    const missing = Array.from(missingKeys);
    if (missing.length === 0) return true;
    const questions = missing.reduce(
      (acc, key) => ({ ...acc, [key]: { type: 'string' as const } }),
      {} as Record<string, { type: 'string' }>,
    );
    const answer = await this.askUserInput(
      `Need input to continue:\n${missing.join('\n')}`,
      questions,
    );
    const values = answer ?? {};
    const allEmpty = Object.values(values).every(
      (v) => !String(v ?? '').trim(),
    );
    if (allEmpty) {
      this.stopPrompt(requestId);
      return false;
    }
    run.args = { ...run.args, ...values };
    return true;
  }

  private async handleBotherUserAction(
    requestId: number,
    run: PromptRun,
    nextAction: WireActionWithWaitAndRec,
  ) {
    try {
      const action: any = nextAction.action as any;
      const missingInfos: string[] = Array.isArray(action.missingInfos)
        ? action.missingInfos
        : [];

      const questions =
        missingInfos.length > 0
          ? missingInfos.reduce(
              (acc, key) => ({ ...acc, [key]: { type: 'string' as const } }),
              {} as Record<string, { type: 'string' }>,
            )
          : { input: { type: 'string' as const } };

      const message =
        typeof action.warn === 'string' && action.warn.trim().length
          ? action.warn
          : 'Input required to continue';

      const answer = await this.askUserInput(message, questions as any);
      const values = answer ?? {};
      const allEmpty = Object.values(values).every(
        (v) => !String(v ?? '').trim(),
      );
      if (allEmpty) {
        this.stopPrompt(requestId);
        return;
      }
      run.args = { ...run.args, ...values };
      this.actionDone(nextAction.id, values);
    } catch (err) {
      console.error('User input failed:', err);
      this.stopPrompt(requestId);
    }
  }

  private pump() {
    if (this.activeRequestId !== null) {
      if (this.inFlightAction) return;
      const run = this.runsByRequestId.get(this.activeRequestId);
      if (!run || run.stopRequested) {
        this.activeRequestId = null;
        this.inFlightAction = false;
        this.scheduleSnapshotEmit();
        this.pump();
        return;
      }
      const nextAction = run.getNextAction();
      if (!nextAction) return;
      this.inFlightAction = true;
      this.dispatchAction(nextAction, this.activeRequestId!, run);
    }

    while (this.runQueue.length) {
      const requestId = this.runQueue.shift()!;
      const run = this.runsByRequestId.get(requestId);
      if (!run || run.stopRequested) continue;
      const nextAction = run.getNextAction();
      if (!nextAction) continue;

      this.activeRequestId = requestId;
      this.inFlightAction = true;
      this.scheduleSnapshotEmit();
      this.dispatchAction(nextAction, requestId, run);
    }
  }

  private dispatchAction(
    nextAction: WireActionWithWaitAndRec,
    requestId: number,
    run: PromptRun,
  ) {
    if ((nextAction.action as any)?.k === 'tab') {
      this.handleTabAction(
        nextAction.id,
        nextAction.action as WireTabAction,
        run.args,
      );
      return;
    }
    if ((nextAction.action as any)?.k === 'botherUser') {
      this.handleBotherUserAction(requestId, run, nextAction);
      return;
    }
    (async () => {
      // const ok = await this.ensureArgsForAction(requestId, run, nextAction);
      // if (!ok) return;
      // if (DEBUG_CONFIRM_ALL_ACTIONS || nextAction.risk === 'h') {
      //   await this.confirmAndDispatchHighRiskAction(requestId, run, nextAction);
      //   return;
      // }
      this.focusedTab!.pushActions([nextAction], run.args);
    })();
  }

  private cleanupActionMapForRequest(requestId: number) {
    for (const [actionId, owner] of this.actionIdToRequestId.entries()) {
      if (owner === requestId) this.actionIdToRequestId.delete(actionId);
    }
  }

  private scheduleSnapshotEmit() {
    if (this.snapshotTimer) {
      this.snapshotPending = true;
      return;
    }
    this.snapshotTimer = setTimeout(() => {
      this.snapshotTimer = null;
      this.snapshotPending = false;
      this.focusedTab?.emitLlmSessionSnapshot(this.getSnapshot());
      if (this.snapshotPending) {
        this.scheduleSnapshotEmit();
      }
    }, 150);
  }

  getSnapshot() {
    const runs = Array.from(this.runsByRequestId.values())
      .slice()
      .sort((a, b) => a.requestId - b.requestId)
      .map((run) => ({
        requestId: run.requestId,
        stopRequested: run.stopRequested,
        args: run.args,
        actions: run.actions.map((action) => ({
          id: action.id,
          intent: action.intent,
          risk: action.risk,
          done: action.done,
          error: action.error,
          stepPrompt: action.stepPrompt,
          promptId: action.promptId,
          argsDelta: action.argsDelta,
          action: action.action,
        })),
        currentAction: run.currentAction,
        prompts: run.prompts.map((prompt) => ({
          id: prompt.id,
          parentId: prompt.parentId,
          sessionId: prompt.sessionId,
          goalPrompt: prompt.goalPrompt,
          subPrompt: prompt.subPrompt,
          argsAdded: prompt.argsAdded ?? null,
          complexity: prompt.complexity,
        })),
        breakPromptForExeErr: run.breakPromptForExeErr,
        fixingAction: run.fixingAction.length
          ? run.fixingAction.map((f) => ({
              actionId: f.action.id,
              offset: f.offset,
              promptId: f.promptId,
            }))
          : [],
        sessionQueue: run.sessionQueue.map((session) => ({
          id: session.id,
          parentId: session.parent?.id ?? null,
          promptQueue: session.promptQueue.map((prompt) => ({
            id: prompt.id,
            parentId: prompt.parentId,
            sessionId: prompt.sessionId,
            goalPrompt: prompt.goalPrompt,
            subPrompt: prompt.subPrompt,
            argsAdded: prompt.argsAdded ?? null,
            complexity: prompt.complexity,
          })),
          subSessionQueueIds: session.subSessionQueue.map((s) => s.id),
          breakPromptForExeErr: session.breakPromptForExeErr,
        })),
        runningSessionIds: run.runningSession.map((session) => session.id),
      }));
    return {
      activeRequestId: this.activeRequestId,
      runQueue: [...this.runQueue],
      runs,
    };
  }

  private cleanupTab(frameId: number) {
    const wvTab = this.getTab(frameId);
    if (wvTab) {
      try {
        wvTab.stopPrompt();
      } catch {
        // ignore cleanup errors
      }
      try {
        wvTab.webView.setVisible(false);
      } catch {
        // ignore cleanup errors
      }
      try {
        this.mainWindow?.contentView.removeChildView(wvTab.webView);
      } catch {
        // ignore cleanup errors
      }
      this.unregisterTab(frameId);
    }

    try {
      this.mainWindow?.webContents.send('tab-closed', { frameId });
    } catch {
      // ignore teardown errors
    }
  }

  private handleTabAction(
    actionId: number,
    action: WireTabAction,
    args: Record<string, string>,
  ) {
    ToRendererIpc.tab.send(this.mainWindow.webContents, {
      tabId: action.id,
      url: action.url ? CommonUtil.replaceJsTpl(action.url, args) : undefined,
      actionId,
      triggerFrameId: this.focusedTab!.webView.webContents.id,
    });
  }
}
