import './widget/calendar/calendar';
import './widget/combobox/combobox';
import './widget/email';
import './widget/fileUpload';
import './widget/form/form';
import './widget/list';
import './widget/iframe';
import './widget/messager';
import './widget/slider';
